package co.gov.ideam.snif.integracion.webservices.consultarpermisos;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebServiceClient(wsdlLocation="http://181.225.72.78:8080/snif-integra-ws-web/WS_IDEAM_SNIF_ConsultarPermisos?WSDL",
  targetNamespace="http://consultarPermisos.webservices.integracion.snif.ideam.gov.co/",
  name="WS_IDEAM_SNIF_ConsultarPermisos")
public class WS_IDEAM_SNIF_ConsultarPermisos
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("co.gov.ideam.snif.integracion.webservices.consultarpermisos.WS_IDEAM_SNIF_ConsultarPermisos");
      URL baseUrl = WS_IDEAM_SNIF_ConsultarPermisos.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            WS_IDEAM_SNIF_ConsultarPermisos.class.getResource("http://181.225.72.78:8080/snif-integra-ws-web/WS_IDEAM_SNIF_ConsultarPermisos?WSDL");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "http://181.225.72.78:8080/snif-integra-ws-web/WS_IDEAM_SNIF_ConsultarPermisos?WSDL");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "http://181.225.72.78:8080/snif-integra-ws-web/WS_IDEAM_SNIF_ConsultarPermisos?WSDL");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://181.225.72.78:8080/snif-integra-ws-web/WS_IDEAM_SNIF_ConsultarPermisos?WSDL",
          e);
    }
  }

  public WS_IDEAM_SNIF_ConsultarPermisos()
  {
    super(wsdlLocationURL,
          new QName("http://consultarPermisos.webservices.integracion.snif.ideam.gov.co/",
                    "WS_IDEAM_SNIF_ConsultarPermisos"));
  }

  public WS_IDEAM_SNIF_ConsultarPermisos(URL wsdlLocation,
                                         QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="WSConsultarPermisosPort")
  public co.gov.ideam.snif.integracion.webservices.consultarpermisos.WSConsultarPermisos getWSConsultarPermisosPort()
  {
    return (co.gov.ideam.snif.integracion.webservices.consultarpermisos.WSConsultarPermisos) super.getPort(new QName("http://consultarPermisos.webservices.integracion.snif.ideam.gov.co/",
                                                                                                                     "WSConsultarPermisosPort"),
                                                                                                           co.gov.ideam.snif.integracion.webservices.consultarpermisos.WSConsultarPermisos.class);
  }

  @WebEndpoint(name="WSConsultarPermisosPort")
  public co.gov.ideam.snif.integracion.webservices.consultarpermisos.WSConsultarPermisos getWSConsultarPermisosPort(WebServiceFeature... features)
  {
    return (co.gov.ideam.snif.integracion.webservices.consultarpermisos.WSConsultarPermisos) super.getPort(new QName("http://consultarPermisos.webservices.integracion.snif.ideam.gov.co/",
                                                                                                                     "WSConsultarPermisosPort"),
                                                                                                           co.gov.ideam.snif.integracion.webservices.consultarpermisos.WSConsultarPermisos.class,
                                                                                                           features);
  }
}
