package co.gov.ideam.snif.integracion.webservices.consultarpermisos;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebService(wsdlLocation="http://181.225.72.78:8080/snif-integra-ws-web/WS_IDEAM_SNIF_ConsultarPermisos?WSDL",
  targetNamespace="http://consultarPermisos.webservices.integracion.snif.ideam.gov.co/",
  name="WSConsultarPermisos")
@XmlSeeAlso(
  { co.gov.ideam.snif.integracion.webservices.consultarpermisos.ObjectFactory.class })
public interface WSConsultarPermisos
{
  @WebMethod
  @Action(input="http://consultarPermisos.webservices.integracion.snif.ideam.gov.co/WSConsultarPermisos/consultarPermisos",
    output="http://consultarPermisos.webservices.integracion.snif.ideam.gov.co/WSConsultarPermisos/consultarPermisosResponse")
  @ResponseWrapper(localName="consultarPermisosResponse", targetNamespace="http://consultarPermisos.webservices.integracion.snif.ideam.gov.co/",
    className="co.gov.ideam.snif.integracion.webservices.consultarpermisos.ConsultarPermisosResponse")
  @RequestWrapper(localName="consultarPermisos", targetNamespace="http://consultarPermisos.webservices.integracion.snif.ideam.gov.co/",
    className="co.gov.ideam.snif.integracion.webservices.consultarpermisos.ConsultarPermisos")
  @WebResult(targetNamespace="")
  public co.gov.ideam.snif.integracion.webservices.consultarpermisos.OsConsultarPermisos consultarPermisos(@WebParam(targetNamespace="",
      name="objetoEntrada")
    co.gov.ideam.snif.integracion.webservices.consultarpermisos.OeConsultarPermisos objetoEntrada);
}
