package co.gov.ideam.snif.integracion.webservices.consultarpermisos;

import javax.xml.ws.WebServiceRef;
// !THE CHANGES MADE TO THIS FILE WILL BE DESTROYED IF REGENERATED!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

public class WSConsultarPermisosPortClient
{
  @WebServiceRef
  private static WS_IDEAM_SNIF_ConsultarPermisos wS_IDEAM_SNIF_ConsultarPermisos;

  public static void main(String [] args)
  {
    wS_IDEAM_SNIF_ConsultarPermisos = new WS_IDEAM_SNIF_ConsultarPermisos();
    WSConsultarPermisos wSConsultarPermisos = wS_IDEAM_SNIF_ConsultarPermisos.getWSConsultarPermisosPort();
    // Add your code to call the desired methods.
  }
}
