package co.gov.ideam.sirh.webservices.businessl.registrarpermiso;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebServiceClient(wsdlLocation="http://129.144.6.77:8001/WS_SIRH_RegistrarPermiso/proxy/RegistrarPermisoProxy?wsdl",
  targetNamespace="http://registrarPermiso.businessl.webservices.sirh.ideam.gov.co/",
  name="WS_SIAC_SIRH_RegistrarPermiso")
public class WS_SIAC_SIRH_RegistrarPermiso_Service
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("co.gov.ideam.sirh.webservices.businessl.registrarpermiso.WS_SIAC_SIRH_RegistrarPermiso_Service");
      URL baseUrl =
        WS_SIAC_SIRH_RegistrarPermiso_Service.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            WS_SIAC_SIRH_RegistrarPermiso_Service.class.getResource("http://129.144.6.77:8001/WS_SIRH_RegistrarPermiso/proxy/RegistrarPermisoProxy?wsdl");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "http://129.144.6.77:8001/WS_SIRH_RegistrarPermiso/proxy/RegistrarPermisoProxy?wsdl");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "http://129.144.6.77:8001/WS_SIRH_RegistrarPermiso/proxy/RegistrarPermisoProxy?wsdl");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://129.144.6.77:8001/WS_SIRH_RegistrarPermiso/proxy/RegistrarPermisoProxy?wsdl",
          e);
    }
  }

  public WS_SIAC_SIRH_RegistrarPermiso_Service()
  {
    super(wsdlLocationURL,
          new QName("http://registrarPermiso.businessl.webservices.sirh.ideam.gov.co/",
                    "WS_SIAC_SIRH_RegistrarPermiso"));
  }

  public WS_SIAC_SIRH_RegistrarPermiso_Service(URL wsdlLocation,
                                               QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="RegistrarPermisoSirhPort")
  public co.gov.ideam.sirh.webservices.businessl.registrarpermiso.WS_SIAC_SIRH_RegistrarPermiso getRegistrarPermisoSirhPort()
  {
    return (co.gov.ideam.sirh.webservices.businessl.registrarpermiso.WS_SIAC_SIRH_RegistrarPermiso) super.getPort(new QName("http://registrarPermiso.businessl.webservices.sirh.ideam.gov.co/",
                                                                                                                            "RegistrarPermisoSirhPort"),
                                                                                                                  co.gov.ideam.sirh.webservices.businessl.registrarpermiso.WS_SIAC_SIRH_RegistrarPermiso.class);
  }

  @WebEndpoint(name="RegistrarPermisoSirhPort")
  public co.gov.ideam.sirh.webservices.businessl.registrarpermiso.WS_SIAC_SIRH_RegistrarPermiso getRegistrarPermisoSirhPort(WebServiceFeature... features)
  {
    return (co.gov.ideam.sirh.webservices.businessl.registrarpermiso.WS_SIAC_SIRH_RegistrarPermiso) super.getPort(new QName("http://registrarPermiso.businessl.webservices.sirh.ideam.gov.co/",
                                                                                                                            "RegistrarPermisoSirhPort"),
                                                                                                                  co.gov.ideam.sirh.webservices.businessl.registrarpermiso.WS_SIAC_SIRH_RegistrarPermiso.class,
                                                                                                                  features);
  }
}
