package co.gov.ideam.sirh.webservices.businessl.consultarpermisos;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebServiceClient(wsdlLocation="http://181.225.72.35:8230/Ideam-Ejb/WS_SIAC_SIRH_ConsultarPermisos/WS_SIAC_SIRH_ConsultarPermisos?WSDL",
  targetNamespace="http://consultarPermisos.businessl.webservices.sirh.ideam.gov.co/",
  name="WS_SIAC_SIRH_ConsultarPermisos")
public class WS_SIAC_SIRH_ConsultarPermisos_Service
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("co.gov.ideam.sirh.webservices.businessl.consultarpermisos.WS_SIAC_SIRH_ConsultarPermisos_Service");
      URL baseUrl =
        WS_SIAC_SIRH_ConsultarPermisos_Service.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            WS_SIAC_SIRH_ConsultarPermisos_Service.class.getResource("http://181.225.72.35:8230/Ideam-Ejb/WS_SIAC_SIRH_ConsultarPermisos/WS_SIAC_SIRH_ConsultarPermisos?WSDL");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "http://181.225.72.35:8230/Ideam-Ejb/WS_SIAC_SIRH_ConsultarPermisos/WS_SIAC_SIRH_ConsultarPermisos?WSDL");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "http://181.225.72.35:8230/Ideam-Ejb/WS_SIAC_SIRH_ConsultarPermisos/WS_SIAC_SIRH_ConsultarPermisos?WSDL");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://181.225.72.35:8230/Ideam-Ejb/WS_SIAC_SIRH_ConsultarPermisos/WS_SIAC_SIRH_ConsultarPermisos?WSDL",
          e);
    }
  }

  public WS_SIAC_SIRH_ConsultarPermisos_Service()
  {
    super(wsdlLocationURL,
          new QName("http://consultarPermisos.businessl.webservices.sirh.ideam.gov.co/",
                    "WS_SIAC_SIRH_ConsultarPermisos"));
  }

  public WS_SIAC_SIRH_ConsultarPermisos_Service(URL wsdlLocation,
                                                QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="ConsultarPermisoSirhPort")
  public co.gov.ideam.sirh.webservices.businessl.consultarpermisos.WS_SIAC_SIRH_ConsultarPermisos getConsultarPermisoSirhPort()
  {
    return (co.gov.ideam.sirh.webservices.businessl.consultarpermisos.WS_SIAC_SIRH_ConsultarPermisos) super.getPort(new QName("http://consultarPermisos.businessl.webservices.sirh.ideam.gov.co/",
                                                                                                                              "ConsultarPermisoSirhPort"),
                                                                                                                    co.gov.ideam.sirh.webservices.businessl.consultarpermisos.WS_SIAC_SIRH_ConsultarPermisos.class);
  }

  @WebEndpoint(name="ConsultarPermisoSirhPort")
  public co.gov.ideam.sirh.webservices.businessl.consultarpermisos.WS_SIAC_SIRH_ConsultarPermisos getConsultarPermisoSirhPort(WebServiceFeature... features)
  {
    return (co.gov.ideam.sirh.webservices.businessl.consultarpermisos.WS_SIAC_SIRH_ConsultarPermisos) super.getPort(new QName("http://consultarPermisos.businessl.webservices.sirh.ideam.gov.co/",
                                                                                                                              "ConsultarPermisoSirhPort"),
                                                                                                                    co.gov.ideam.sirh.webservices.businessl.consultarpermisos.WS_SIAC_SIRH_ConsultarPermisos.class,
                                                                                                                    features);
  }
}
