package co.gov.ideam.sirh.webservices.businessl.consultarfuncionarios;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebService(wsdlLocation="http://129.144.6.77:8001/WS_SIRH_ConsultarFuncionarios/proxy/ConsultarFuncionariosProxy?wsdl",
  targetNamespace="http://consultarFuncionarios.businessl.webservices.sirh.ideam.gov.co/",
  name="WS_SIAC_SIRH_ConsultarFuncionarios")
@XmlSeeAlso(
  { co.gov.ideam.sirh.webservices.businessl.consultarfuncionarios.ObjectFactory.class })
public interface WS_SIAC_SIRH_ConsultarFuncionarios
{
  @WebMethod
  @Action(input="http://consultarFuncionarios.businessl.webservices.sirh.ideam.gov.co/WS_SIAC_SIRH_ConsultarFuncionarios/consultarFuncionarios",
    output="http://consultarFuncionarios.businessl.webservices.sirh.ideam.gov.co/WS_SIAC_SIRH_ConsultarFuncionarios/consultarFuncionariosResponse")
  @ResponseWrapper(localName="consultarFuncionariosResponse",
    targetNamespace="http://consultarFuncionarios.businessl.webservices.sirh.ideam.gov.co/",
    className="co.gov.ideam.sirh.webservices.businessl.consultarfuncionarios.ConsultarFuncionariosResponse")
  @RequestWrapper(localName="consultarFuncionarios", targetNamespace="http://consultarFuncionarios.businessl.webservices.sirh.ideam.gov.co/",
    className="co.gov.ideam.sirh.webservices.businessl.consultarfuncionarios.ConsultarFuncionarios")
  @WebResult(targetNamespace="", name="funcionarios")
  public co.gov.ideam.sirh.webservices.businessl.consultarfuncionarios.OsConsultarFuncionarios consultarFuncionarios(@WebParam(targetNamespace="",
      name="arg0")
    co.gov.ideam.sirh.webservices.businessl.consultarfuncionarios.OeConsultarFuncionarios arg0);
}
