package co.gov.ideam.integracion.snif.webservices.funcionarios;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebServiceClient(wsdlLocation="http://181.225.72.78:8080/SNIF-SIAC-WS-web/WS_IDEAM_SNIF_ConsultarFuncionarios?WSDL",
  targetNamespace="http://funcionarios.webservices.snif.integracion.ideam.gov.co/",
  name="WS_IDEAM_SNIF_ConsultarFuncionarios")
public class WS_IDEAM_SNIF_ConsultarFuncionarios
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("co.gov.ideam.integracion.snif.webservices.funcionarios.WS_IDEAM_SNIF_ConsultarFuncionarios");
      URL baseUrl =
        WS_IDEAM_SNIF_ConsultarFuncionarios.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            WS_IDEAM_SNIF_ConsultarFuncionarios.class.getResource("http://181.225.72.78:8080/SNIF-SIAC-WS-web/WS_IDEAM_SNIF_ConsultarFuncionarios?WSDL");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "http://181.225.72.78:8080/SNIF-SIAC-WS-web/WS_IDEAM_SNIF_ConsultarFuncionarios?WSDL");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "http://181.225.72.78:8080/SNIF-SIAC-WS-web/WS_IDEAM_SNIF_ConsultarFuncionarios?WSDL");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://181.225.72.78:8080/SNIF-SIAC-WS-web/WS_IDEAM_SNIF_ConsultarFuncionarios?WSDL",
          e);
    }
  }

  public WS_IDEAM_SNIF_ConsultarFuncionarios()
  {
    super(wsdlLocationURL,
          new QName("http://funcionarios.webservices.snif.integracion.ideam.gov.co/",
                    "WS_IDEAM_SNIF_ConsultarFuncionarios"));
  }

  public WS_IDEAM_SNIF_ConsultarFuncionarios(URL wsdlLocation,
                                             QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="WSConsultarFuncionarioPort")
  public co.gov.ideam.integracion.snif.webservices.funcionarios.WSConsultarFuncionario getWSConsultarFuncionarioPort()
  {
    return (co.gov.ideam.integracion.snif.webservices.funcionarios.WSConsultarFuncionario) super.getPort(new QName("http://funcionarios.webservices.snif.integracion.ideam.gov.co/",
                                                                                                                   "WSConsultarFuncionarioPort"),
                                                                                                         co.gov.ideam.integracion.snif.webservices.funcionarios.WSConsultarFuncionario.class);
  }

  @WebEndpoint(name="WSConsultarFuncionarioPort")
  public co.gov.ideam.integracion.snif.webservices.funcionarios.WSConsultarFuncionario getWSConsultarFuncionarioPort(WebServiceFeature... features)
  {
    return (co.gov.ideam.integracion.snif.webservices.funcionarios.WSConsultarFuncionario) super.getPort(new QName("http://funcionarios.webservices.snif.integracion.ideam.gov.co/",
                                                                                                                   "WSConsultarFuncionarioPort"),
                                                                                                         co.gov.ideam.integracion.snif.webservices.funcionarios.WSConsultarFuncionario.class,
                                                                                                         features);
  }
}
