package co.gov.ideam.integracion.snif.webservices.funcionarios;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebService(wsdlLocation="http://181.225.72.78:8080/SNIF-SIAC-WS-web/WS_IDEAM_SNIF_ConsultarFuncionarios?WSDL",
  targetNamespace="http://funcionarios.webservices.snif.integracion.ideam.gov.co/",
  name="WSConsultarFuncionario")
@XmlSeeAlso(
  { co.gov.ideam.integracion.snif.webservices.funcionarios.ObjectFactory.class })
public interface WSConsultarFuncionario
{
  @WebMethod
  @Action(input="http://funcionarios.webservices.snif.integracion.ideam.gov.co/WSConsultarFuncionario/consultarFuncionariosAutoridad",
    output="http://funcionarios.webservices.snif.integracion.ideam.gov.co/WSConsultarFuncionario/consultarFuncionariosAutoridadResponse")
  @ResponseWrapper(localName="consultarFuncionariosAutoridadResponse",
    targetNamespace="http://funcionarios.webservices.snif.integracion.ideam.gov.co/",
    className="co.gov.ideam.integracion.snif.webservices.funcionarios.ConsultarFuncionariosAutoridadResponse")
  @RequestWrapper(localName="consultarFuncionariosAutoridad",
    targetNamespace="http://funcionarios.webservices.snif.integracion.ideam.gov.co/",
    className="co.gov.ideam.integracion.snif.webservices.funcionarios.ConsultarFuncionariosAutoridad")
  @WebResult(targetNamespace="")
  public co.gov.ideam.integracion.snif.webservices.funcionarios.OsConsultarFuncionarios consultarFuncionariosAutoridad(@WebParam(targetNamespace="",
      name="objetoEntrada")
    co.gov.ideam.integracion.snif.webservices.funcionarios.OeConsultarFuncionarios objetoEntrada);
}
