package co.gov.ideam.rua.electrico.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebService(wsdlLocation="http://181.225.72.108:9130/RUA/faces/WS_IDEAM_RUA_ConsultarFuncionarios?wsdl",
  targetNamespace="http://webservices.electrico.rua.ideam.gov.co/", name="WS_IDEAM_RUA_ConsultarFuncionarios")
@XmlSeeAlso(
  { ObjectFactory.class })
public interface WS_IDEAM_RUA_ConsultarFuncionarios
{
  @WebMethod
  @Action(input="http://webservices.electrico.rua.ideam.gov.co/WS_IDEAM_RUA_ConsultarFuncionarios/funcionarios",
    output="http://webservices.electrico.rua.ideam.gov.co/WS_IDEAM_RUA_ConsultarFuncionarios/funcionariosResponse")
  @ResponseWrapper(localName="funcionariosResponse", targetNamespace="http://webservices.electrico.rua.ideam.gov.co/",
    className="co.gov.ideam.rua.electrico.webservices.FuncionariosResponse")
  @RequestWrapper(localName="funcionarios", targetNamespace="http://webservices.electrico.rua.ideam.gov.co/",
    className="co.gov.ideam.rua.electrico.webservices.Funcionarios")
  @WebResult(targetNamespace="")
  public co.gov.ideam.rua.electrico.webservices.OsFuncionarios funcionarios(@WebParam(targetNamespace="",
      name="objetoEntrada")
    co.gov.ideam.rua.electrico.webservices.OeFuncionarios objetoEntrada);
}
