package co.gov.ideam.rua.electrico.webservices;

import javax.xml.ws.WebServiceRef;
// !THE CHANGES MADE TO THIS FILE WILL BE DESTROYED IF REGENERATED!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

public class WS_IDEAM_RUA_RegistrarPermisoPortClient
{
  @WebServiceRef
  private static WS_IDEAM_RUA_RegistrarPermiso_Service wS_IDEAM_RUA_RegistrarPermiso_Service;

  public static void main(String [] args)
  {
    wS_IDEAM_RUA_RegistrarPermiso_Service = new WS_IDEAM_RUA_RegistrarPermiso_Service();
    WS_IDEAM_RUA_RegistrarPermiso wS_IDEAM_RUA_RegistrarPermiso = wS_IDEAM_RUA_RegistrarPermiso_Service.getWS_IDEAM_RUA_RegistrarPermisoPort();
    // Add your code to call the desired methods.
  }
}
