package co.gov.ideam.rua.electrico.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebService(wsdlLocation="http://129.144.6.77:8001/WS_RUA_RegistrarPermiso/proxy/RegistrarPermisoProxy?wsdl",
  targetNamespace="http://webservices.electrico.rua.ideam.gov.co/", name="WS_IDEAM_RUA_RegistrarPermiso")
@XmlSeeAlso(
  { co.gov.ideam.rua.electrico.webservices.ObjectFactory.class })
public interface WS_IDEAM_RUA_RegistrarPermiso
{
  @WebMethod
  @Action(input="http://webservices.electrico.rua.ideam.gov.co/WS_IDEAM_RUA_RegistrarPermiso/registrarPermiso",
    output="http://webservices.electrico.rua.ideam.gov.co/WS_IDEAM_RUA_RegistrarPermiso/registrarPermisoResponse")
  @ResponseWrapper(localName="registrarPermisoResponse", targetNamespace="http://webservices.electrico.rua.ideam.gov.co/",
    className="co.gov.ideam.rua.electrico.webservices.RegistrarPermisoResponse")
  @RequestWrapper(localName="registrarPermiso", targetNamespace="http://webservices.electrico.rua.ideam.gov.co/",
    className="co.gov.ideam.rua.electrico.webservices.RegistrarPermiso")
  @WebResult(targetNamespace="")
  public co.gov.ideam.rua.electrico.webservices.OsRegistrarPermiso registrarPermiso(@WebParam(targetNamespace="",
      name="objetoEntrada")
    co.gov.ideam.rua.electrico.webservices.OeRegistrarPermiso objetoEntrada);
}
